<?php


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\CodeRegroupementPrincipal;
use App\CodeRegroupementSecondaire;

class CodeRegroupementSecondaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }

    private static $codes_secondaires = [
		// ['A', 'A01', 'PARTICIP-EMPLOYEUR-FRAIS', 'Remboursement frais-Particip-Employeur', 'M'],
		// ['A', 'A02', 'PARTICIP-EMPLOYEUR-REPAS', 'Titres Restaurant', 'M'],
		// ['A', 'A10', 'INTERESSEMENT', 'Intéressement Annuel', 'A'],
		// ['A', 'A11', 'INTERESSEMENT', 'Intéressement Semestriel', 'S'],
		// ['A', 'A12', 'INTERESSEMENT', 'Intéressement Trimestriel', 'T'],
		// ['A', 'A13', 'INTERESSEMENT', 'Intéressement Mensuel', 'M'],
		// ['A', 'AN1', 'AVANTAGE EN NATURE', 'Avantage en nature Logement', 'M'],
		// ['A', 'AN2', 'AVANTAGE EN NATURE', 'Avantage en nature Véhicule', 'M'],
		// ['A', 'AN3', 'AVANTAGE EN NATURE', 'Avantage en nature Nourriture', 'M'],
		// ['A', 'AN4', 'AVANTAGE EN NATURE', 'Avantage en nature Autre', 'M'],
		// ['A', 'PA1', 'PARTICIPATION', 'Participation', 'A'],
		// ['B', 'B01', 'BASE', 'Brut mensuel de base', 'M'],
		// ['B', 'B02', 'BASE', 'Brut mensuel forfaitaire', 'M'],
		// ['B', 'B03', 'BONUS', 'Bonus annuel', 'A'],
		// ['B', 'B04', 'BONUS', 'Bonus semestriel', 'S'],
		// ['B', 'B11', 'BASE-ABS-AT-MP', 'Déduction absence Accident-Maladie Pro', 'M'],
		// ['B', 'B12', 'BASE-ABS-MALADIE', 'Déduction absence maladie', 'M'],
		// ['B', 'B13', 'BASE-ABS-MATERNITE', 'Déduction absence maternité', 'M'],
		// ['B', 'B14', 'BASE-ABS-RETARD', 'Déduction absence retard', 'M'],
		// ['B', 'C10', 'COMMISSION', 'Commission annuelle', 'A'],
		// ['B', 'C11', 'COMMISSION', 'Commission semestrielle', 'S'],
		// ['B', 'C12', 'COMMISSION', 'Commission trimestrielle', 'T'],
		// ['B', 'C13', 'COMMISSION', 'Commission mensuelle', 'M'],
		// ['B', 'C20', 'CONGES', '10ème de Congés Payés', 'C'],
		// ['B', 'C21', 'CONGES', 'Paiement de congés-RTT-CET', 'E'],
		// ['B', 'C22', 'CONGES', 'Paiement de congés-RTT-CET-départ', 'U'],
		// ['B', 'H01', 'HEURES', 'Paiement d\'heures-en-compteur', 'E'],
		// ['B', 'H10', 'HEURES COMPL', 'Heures complémentaires100', 'M'],
		// ['B', 'H11', 'HEURES SUPPL', 'Heures supplémentaires110', 'M'],
		// ['B', 'H12', 'HEURES SUPPL', 'Heures supplémentaires125', 'M'],
		// ['B', 'H13', 'HEURES SUPPL', 'Heures supplémentaires120', 'M'],
		// ['B', 'H15', 'HEURES SUPPL', 'Heures supplémentaires150', 'M'],
		// ['B', 'H20', 'HEURES SUPPL', 'Heures supplémentaires200', 'M'],
		// ['B', 'H99', 'HEURES', 'Paiement d\'heures-en-compteur-départ', 'U'],
		// ['B', 'ICR', 'INDEMNITE', 'Indemnité de reclassement', 'M'],
		// ['B', 'IST', 'INDEMNITE-STAGE', 'Indemnité de stage', 'M'],
		// ['B', 'P01', 'PRIME', 'Prime mensuelle permanente', 'M'],
		// ['B', 'P02', 'PRIME', 'Prime d\'Ancienneté', 'M'],
		// ['B', 'P10', 'PRIME', 'Prime annuelle', 'A'],
		// ['B', 'P11', 'PRIME', 'Prime Semestrielle', 'S'],
		// ['B', 'P12', 'PRIME', 'Prime trimestrielle', 'T'],
		// ['B', 'P13', 'PRIME', 'Prime mensuelle conditionnée', 'M'],
		// ['B', 'P20', 'PRIME', 'Prime hebdomadaire', 'H'],
		// ['B', 'P21', 'PRIME', 'Prime journalière', 'J'],
		// ['B', 'P99', 'PRIME', 'Prime exceptionnelle', 'E'],
		// ['B', 'PRA', 'PREAVIS', 'Indemnité de préavis', 'M'],
		// ['C', 'C90', 'ALLOCATIONS', 'Allocations familiales', 'M'],
		// ['C', 'C91', 'PREVOYANCE-INVAL', 'Cotisations Incapcité-Invalidité-Décès', 'M'],
		// ['C', 'C92', 'PREVOYANCE-SANTE', 'Cotisations Mutuelle', 'M'],
		// ['C', 'C93', 'RETRAITE', 'Cotisations retraite', 'M'],
		// ['C', 'C931', 'RETRAITE', 'Cotisation retraite TA', 'M'],
		// ['C', 'C932', 'RETRAITE', 'Cotisation retraite TB', 'M'],
		// ['C', 'C933', 'RETRAITE', 'Cotisation retraite TC', 'M'],
		// ['C', 'C94', 'TAUX-AT-MP', 'Cotisations Accident du Travail - Maladie professionnelle', 'M'],
		// ['C', 'C95', 'TAXES', 'Autres cotisations-Taxes', 'M'],
		// ['C', 'C99', 'TOTAL', 'Charges Patronales', 'M'],
		// ['D', 'CSG', 'TAXES', 'CSG-CRDS', 'M'],
		// ['F', 'FR1', 'FRAIS', 'Remboursement frais hors déplacement', 'M'],
		// ['F', 'FR2', 'FRAIS-DEPL', 'Indemnité de déplacement', 'M'],
		// ['F', 'FR3', 'INDEMNITE-REPAS', 'Indemnité de Repas', 'U'],
		// ['I', 'ILI', 'INDEMNITE-LIC', 'Indemnité de licenciement', 'U'],
		// ['I', 'ILS', 'INDEMNITE-LIC-SUP', 'Indemnité de licenciement-Supra-Légale', 'U'],
		// ['I', 'IMR', 'INDEMNITE-MISE-R', 'Indemnité de mise à la retraite', 'U'],
		// ['I', 'IRE', 'INDEMNITE-DEP-R', 'Indemnité de départ à la retraite', 'U'],
		// ['I', 'ITR', 'INDEMNITE-TRANS', 'Indemnité transactionnelle', 'U'],
		// ['N', 'PAN', 'PAIEMENT NET', 'Versement NET', 'M'],
		// ['V', 'FIS', 'PRELEVEMENT A LA SOURCE', 'Prélèvement fiscal à la source', 'M'],
		// ['P', 'PCO', 'INTERVENANT-CONSULTING', 'Intervenant externe-Consulting', 'E'],
		// ['P', 'PEX', 'INTERVENANT-EXPERT', 'Intervenant externe-Expertise-sociale', 'E'],
		// ['P', 'PFO', 'INTERVENANT-FORMATION', 'Intervenant externe-Frais de formation', 'E'],
		// ['P', 'PRG', 'INTERVENANT-REGIE', 'Intervenant externe-Régie', 'M'],
		// ['P', 'PRS', 'INTERVENANT-RECRUTEMENT', 'Intervenant externe-Frais de recrutement', 'E'],
		// ['P', 'PRX', 'INTERVENANT-EXTERNALISATION', 'Intervenant externe-Externalisation', 'M'],
		// ['P', 'TT1', 'TRAVAILTEMPORAIRE', 'Travail Temporaire Accroissement Temporaire', 'M'],
		// ['P', 'TT2', 'TRAVAILTEMPORAIRE', 'Travail Temporaire Commande exceptionnelle', 'M'],
		// ['P', 'TT3', 'TRAVAILTEMPORAIRE', 'Travail Temporaire Remplacement Absent', 'M'],
		// ['P', 'TT4', 'TRAVAILTEMPORAIRE', 'Travail Temporaire Remplacement Attente Embauche', 'M'],
		// ['O', 'PRC', 'CONGES', 'Provision de congés', 'M'],
		// ['O', 'PRE', 'RETRAITE', 'Provision Retraite (IDR)', 'A'],
		// ['O', 'PRI', 'RISQUE', 'Provision pour risque', 'A'],
		// ['O', 'PRT', 'RTT', 'Provision de RTT', 'M'],
		// ['S', 'STA', 'SEUIL TA', 'Seuil Tranche A', 'M'],
		// ['S', 'STB', 'SEUIL TB', 'Seuil Tranche B', 'M'],
		// ['S', 'STC', 'SEUIL TC', 'Seuil Tranche C', 'M'],
		// ['T', 'ETP', 'EQUIVALENT TEMPS PLEIN', 'Equivalent Temps Plein dans le mois', 'M'],
		// ['T', 'JCA', 'JOURS CALENDAIRES', 'Nombre de jours calendaires', 'M'],
		// ['T', 'JOU', 'JOURS OUVRES', 'Nombre de jours ouvrés', 'M'],
		// ['T', 'FDM', 'PRESENT FIN DE MOIS', 'Présent fin de mois', 'M'],
		// ['Z', 'ZGC', 'COUT TOTAL', 'Coût total employeur', 'M'],
		["A", "A01", "PARTICIP-EMPLOYEUR-FRAIS", "Remboursement frais-Particip-Employeur", "M", false],
		["A", "A02", "PARTICIP-EMPLOYEUR-REPAS", "Titres Restaurant", "M", false],
		["A", "A10", "INTERESSEMENT", "Intéressement Annuel", "A", false],
		["A", "A11", "INTERESSEMENT", "Intéressement Semestriel", "S", false],
		["A", "A12", "INTERESSEMENT", "Intéressement Trimestriel", "T", false],
		["A", "A13", "INTERESSEMENT", "Intéressement Mensuel", "M", false],
		["A", "AN1", "AVANTAGE EN NATURE", "Avantage en nature Logement", "M", false],
		["A", "AN2", "AVANTAGE EN NATURE", "Avantage en nature Véhicule", "M", false],
		["A", "AN3", "AVANTAGE EN NATURE", "Avantage en nature Nourriture", "M", false],
		["A", "AN4", "AVANTAGE EN NATURE", "Avantage en nature Autre", "M", false],
		["A", "PA1", "PARTICIPATION", "Participation", "A", false],
		["B", "B01", "BASE", "Brut mensuel de base", "M", true],
		["B", "B02", "BASE", "Brut mensuel forfaitaire", "M", true],
		["B", "B03", "BONUS", "Bonus annuel", "A", true],
		["B", "B04", "BONUS", "Bonus semestriel", "S", true],
		["B", "B11", "BASE-ABS-AT-MP", "Déduction absence Accident-Maladie Pro", "M", true],
		["B", "B12", "BASE-ABS-MALADIE", "Déduction absence maladie", "M", true],
		["B", "B13", "BASE-ABS-MATERNITE", "Déduction absence maternité", "M", true],
		["B", "B14", "BASE-ABS-RETARD", "Déduction absence retard", "M", true],
		["B", "B99", "BASE", "Total brut du mois", "M", true],
		["B", "C10", "COMMISSION", "Commission annuelle", "A", true],
		["B", "C11", "COMMISSION", "Commission semestrielle", "S", true],
		["B", "C12", "COMMISSION", "Commission trimestrielle", "T", true],
		["B", "C13", "COMMISSION", "Commission mensuelle", "M", true],
		["B", "C20", "CONGES", "10ème de Congés Payés", "A", true],
		["B", "C21", "CONGES", "Paiement de congés-RTT-CET", "E", true],
		["B", "C22", "CONGES", "Paiement de congés-RTT-CET-départ", "U", true],
		["B", "H01", "HEURES", "Paiement d'heures-en-compteur", "E", true],
		["B", "H10", "HEURES COMPL", "Heures complémentaires100", "M", true],
		["B", "H11", "HEURES SUPPL", "Heures supplémentaires110", "M", true],
		["B", "H12", "HEURES SUPPL", "Heures supplémentaires125", "M", true],
		["B", "H13", "HEURES SUPPL", "Heures supplémentaires120", "M", true],
		["B", "H15", "HEURES SUPPL", "Heures supplémentaires150", "M", true],
		["B", "H20", "HEURES SUPPL", "Heures supplémentaires200", "M", true],
		["B", "H99", "HEURES", "Paiement d'heures-en-compteur-départ", "U", true],
		["B", "ICR", "INDEMNITE", "Indemnité de reclassement", "M", true],
		["B", "IST", "INDEMNITE-STAGE", "Indemnité de stage", "M", true],
		["B", "P01", "PRIME", "Prime mensuelle permanente", "M", true],
		["B", "P02", "PRIME", "Prime d'Ancienneté", "M", true],
		["B", "P10", "PRIME", "Prime annuelle", "A", true],
		["B", "P11", "PRIME", "Prime Semestrielle", "S", true],
		["B", "P12", "PRIME", "Prime trimestrielle", "T", true],
		["B", "P13", "PRIME", "Prime mensuelle conditionnée", "M", true],
		["B", "P20", "PRIME", "Prime hebdomadaire", "H", true],
		["B", "P21", "PRIME", "Prime journalière", "J", true],
		["B", "P99", "PRIME", "Prime exceptionnelle", "E", true],
		["B", "PRA", "PREAVIS", "Indemnité de préavis", "M", true],
		["C", "C90", "ALLOCATIONS", "Allocations familiales", "M", false],
		["C", "C91", "PREVOYANCE-INVAL", "Cotisations Incapcité-Invalidité-Décès", "M", false],
		["C", "C92", "PREVOYANCE-SANTE", "Cotisations Mutuelle", "M", false],
		["C", "C93", "RETRAITE", "Cotisations retraite", "M", false],
		["C", "C931", "RETRAITE", "Cotisation retraite TA", "M", false],
		["C", "C932", "RETRAITE", "Cotisation retraite TB", "M", false],
		["C", "C933", "RETRAITE", "Cotisation retraite TC", "M", false],
		["C", "C94", "TAUX-AT-MP", "Cotisations Accident du Travail - Maladie professionnelle", "M", false],
		["C", "C95", "TAXES", "Autres cotisations-Taxes", "M", false],
		["C", "C99", "TOTAL", "Total Charges Patronales", "M", false],
		["D", "CSG", "TAXES", "CSG-CRDS", "M", false],
		["F", "FR1", "FRAIS", "Remboursement frais hors déplacement", "M", false],
		["F", "FR2", "FRAIS-DEPL", "Indemnité de déplacement", "M", false],
		["F", "FR3", "INDEMNITE-REPAS", "Indemnité de Repas", "U", false],
		["I", "ILI", "INDEMNITE-LIC", "Indemnité de licenciement", "U", false],
		["I", "ILS", "INDEMNITE-LIC-SUP", "Indemnité de licenciement-Supra-Légale", "U", false],
		["I", "IMR", "INDEMNITE-MISE-R", "Indemnité de mise à la retraite", "U", false],
		["I", "IRE", "INDEMNITE-DEP-R", "Indemnité de départ à la retraite", "U", false],
		["I", "ITR", "INDEMNITE-TRANS", "Indemnité transactionnelle", "U", false],
		["N", "PAN", "PAIEMENT NET", "Versement NET", "M", false],
		["V", "FIS", "PRELEVEMENT A LA SOURCE", "Prélèvement fiscal à la source", "M", false],
		["P", "PCO", "INTERVENANT-CONSULTING", "Intervenant externe-Consulting", "E", false],
		["P", "PEX", "INTERVENANT-EXPERT", "Intervenant externe-Expertise-sociale", "E", false],
		["P", "PFO", "INTERVENANT-FORMATION", "Intervenant externe-Frais de formation", "E", false],
		["P", "PRG", "INTERVENANT-REGIE", "Intervenant externe-Régie", "M", false],
		["P", "PRS", "INTERVENANT-RECRUTEMENT", "Intervenant externe-Frais de recrutement", "E", false],
		["P", "PRX", "INTERVENANT-EXTERNALISATION", "Intervenant externe-Externalisation", "M", false],
		["P", "TT1", "TRAVAILTEMPORAIRE", "Travail Temporaire Accroissement Temporaire", "M", false],
		["P", "TT2", "TRAVAILTEMPORAIRE", "Travail Temporaire Commande exceptionnelle", "M", false],
		["P", "TT3", "TRAVAILTEMPORAIRE", "Travail Temporaire Remplacement Absent", "M", false],
		["P", "TT4", "TRAVAILTEMPORAIRE", "Travail Temporaire Remplacement Attente Embauche", "M", false],
		["O", "PRC", "CONGES", "Provision de congés", "M", true],
		["O", "PRE", "RETRAITE", "Provision Retraite (IDR)", "A", false],
		["O", "PRI", "RISQUE", "Provision pour risque", "A", false],
		["O", "PRT", "RTT", "Provision de RTT", "M", true],
		["S", "STA", "SEUIL TA", "Seuil Tranche A", "M", false],
		["S", "STB", "SEUIL TB", "Seuil Tranche B", "M", false],
		["S", "STC", "SEUIL TC", "Seuil Tranche C", "M", false],
		["E", "ETM", "PRESENT AU COURS DU MOIS", "Présent au cours du mois", "M", false],
		["E", "ETP", "EQUIVALENT TEMPS PLEIN", "Equivalent Temps Plein dans le mois", "M", false],
		["T", "JCA", "JOURS CALENDAIRES", "Nombre de jours calendaires", "M", false],
		["T", "JOU", "JOURS OUVRES", "Nombre de jours ouvrés", "M", false],
		["E", "FDM", "PRESENT FIN DE MOIS", "Présent fin de mois", "M", false],
		["Z", "ZGC", "COUT TOTAL", "Coût total employeur", "M", false],
    ];

    public static function populate()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        CodeRegroupementSecondaire::truncate();
        foreach (CodeRegroupementSecondaireSeeder::$codes_secondaires as $code_secondaire) {
            $code_principal = CodeRegroupementPrincipal::where('abreviation', $code_secondaire[0])->first();
            CodeRegroupementSecondaire::create([
                'code_regroupement_principal' => $code_principal->abreviation,
                'abreviation' => $code_secondaire[1],
                'libelle_principale' => $code_secondaire[2],
                'libelle_secondaire' => $code_secondaire[3],
                'periodicite' => $code_secondaire[4],
                'application_taux_charge' => $code_secondaire[5],
            ]);
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
